#!/usr/bin/env python3
"""Generate lib/gallery-images.ts from the Drive manifest + files on disk.

Run after scripts/import-drive-images.sh:
    python3 scripts/build-gallery-index.py

Categories are inferred from the Drive title / filename. Edit CATEGORY_RULES
to change grouping, or edit the generated file by hand for one-offs.
"""
import os, re, sys
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, 'scripts', 'drive-images.manifest.tsv')
IMAGES = os.path.join(ROOT, 'public', 'images')
OUT = os.path.join(ROOT, 'lib', 'gallery-images.ts')

# Folders that hold real photos worth showing in the gallery
INCLUDE_PREFIXES = ('gallery/', 'captains/', 'species/', 'trips/')
SKIP = {'gallery/extra/group-swordfish-alt.jpg'}  # "not a great pic" per Lakelynn

# First matching rule wins. (regex on lowercased "title filename")
CATEGORY_RULES = [
    ('Captains', r'lake & blake|lake and blake|blake-and-lakelynn|blake w/|blake-|lake w/|lake tuna|lake-tuna|minnow'),
    ('Swordfish', r'sword'),
    ('Tuna', r'tuna|yellow|blackfin'),
    ('Mahi & Wahoo', r'mahi|wahoo'),
    ('Snapper & Grouper', r'snapper|grouper|hind|cobia|amberjack'),
    ('Inshore', r'redfish|inshore|cast net|shrimp boat'),
    ('Families & Groups', r'family|father|son|boy|girl|kid|group|ladies|guys|crew|couple|customers|trip'),
]


def caption_from_title(title: str) -> str:
    t = title.strip()
    t = re.sub(r'\s*-\s*not a great pic\s*$', '', t, flags=re.I)
    t = t.replace('w/', 'with').replace('&', 'and').replace('@', 'at')
    t = re.sub(r'\s+', ' ', t)
    if re.match(r'^img[_ ]?\d+', t, re.I):
        return 'On the water with Devine Sportfishing'
    return t[0].upper() + t[1:]


def category_for(title: str, path: str) -> str:
    hay = f'{title} {path}'.lower()
    for name, pattern in CATEGORY_RULES:
        if re.search(pattern, hay):
            return name
    return 'On the Water'


rows = []
with open(MANIFEST) as f:
    for line in f:
        if not line.strip() or line.startswith('#'):
            continue
        _id, dest, title = line.rstrip('\n').split('\t')
        if not dest.startswith(INCLUDE_PREFIXES) or dest in SKIP:
            continue
        full = os.path.join(IMAGES, dest)
        if not os.path.isfile(full):
            print(f'skip missing {dest}', file=sys.stderr)
            continue
        w, h = Image.open(full).size
        rows.append({
            'src': f'/images/{dest}',
            'alt': caption_from_title(title),
            'category': category_for(title, dest),
            'width': w,
            'height': h,
        })

# Lead with the strongest tiles: captains and tuna first, then the rest in manifest order
order = {'Captains': 0, 'Tuna': 1, 'Swordfish': 2, 'Mahi & Wahoo': 3, 'Snapper & Grouper': 4,
         'Inshore': 5, 'Families & Groups': 6, 'On the Water': 7}
rows.sort(key=lambda r: order.get(r['category'], 9))

cats = []
for r in rows:
    if r['category'] not in cats:
        cats.append(r['category'])

with open(OUT, 'w') as f:
    f.write('// Generated by scripts/build-gallery-index.py. Edit that script (or this file) to change.\n\n')
    f.write('export interface GalleryImage {\n  src: string\n  alt: string\n  category: string\n  width: number\n  height: number\n}\n\n')
    f.write('export const GALLERY_CATEGORIES = [\n  \'All\',\n' + ''.join(f"  '{c}',\n" for c in cats) + ']\n\n')
    f.write('export const GALLERY_IMAGES: GalleryImage[] = [\n')
    for r in rows:
        alt = r['alt'].replace("'", "\\'")
        f.write(f"  {{ src: '{r['src']}', alt: '{alt}', category: '{r['category']}', width: {r['width']}, height: {r['height']} }},\n")
    f.write(']\n')

print(f'wrote {len(rows)} images in {len(cats)} categories -> lib/gallery-images.ts')
