#!/usr/bin/env bash
#
# Import photos from the shared "Devine Sportfishing / Images" Google Drive folder
# into public/images/, converting HEIC -> JPG and resizing for the web.
#
# Usage:
#   scripts/import-drive-images.sh            # download + convert anything missing
#   scripts/import-drive-images.sh --force    # re-download and re-convert everything
#
# Requirements: curl, ImageMagick `convert` with HEIC support (libheif).
# Edit scripts/drive-images.manifest.tsv to change which photo goes where.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/scripts/drive-images.manifest.tsv"
OUT_DIR="$ROOT/public/images"
CACHE_DIR="${DRIVE_CACHE_DIR:-$ROOT/.drive-cache}"
FORCE="${1:-}"

mkdir -p "$OUT_DIR" "$CACHE_DIR"

if ! command -v convert >/dev/null; then
  echo "ImageMagick 'convert' not found" >&2; exit 1
fi
if ! convert -list format | grep -q "HEIC"; then
  echo "ImageMagick is missing HEIC support (libheif)" >&2; exit 1
fi

# Max long-edge size by destination. Large backgrounds get more pixels.
max_size_for() {
  case "$1" in
    hero/*|gallery/hero-bg.*|gallery/sunset-boat.*|gallery/boat-action.*) echo 2400 ;;
    logo*|press/*) echo 1600 ;;
    *) echo 1600 ;;
  esac
}

ok=0; skipped=0; failed=0
MAP_MD="$OUT_DIR/IMAGE-MAP.md"
{
  echo "# Image map"
  echo
  echo "Generated by \`scripts/import-drive-images.sh\` from \`scripts/drive-images.manifest.tsv\`."
  echo "Source: Google Drive > Devine Sportfishing > Images."
  echo
  echo "| Site path | Original Drive title | Drive link |"
  echo "|---|---|---|"
} > "$MAP_MD"

while IFS=$'\t' read -r id dest title; do
  [[ -z "${id:-}" || "$id" == \#* ]] && continue
  dest="${dest%$'\r'}"; title="${title%$'\r'}"
  out="$OUT_DIR/$dest"
  mkdir -p "$(dirname "$out")"
  echo "| \`/images/$dest\` | $title | https://drive.google.com/file/d/$id/view |" >> "$MAP_MD"

  if [[ -f "$out" && "$FORCE" != "--force" ]]; then
    skipped=$((skipped+1)); continue
  fi

  raw="$CACHE_DIR/$id"
  if [[ ! -s "$raw" || "$FORCE" == "--force" ]]; then
    # Files in the folder are shared "anyone with the link", so the public
    # download endpoint works without auth. -L follows the usercontent redirect.
    if ! curl -fsSL --retry 3 --retry-delay 2 \
        -o "$raw" "https://drive.google.com/uc?export=download&id=$id"; then
      echo "FAIL download: $title ($id)" >&2; failed=$((failed+1)); continue
    fi
    # Drive returns an HTML page instead of the file if sharing is off.
    if head -c 512 "$raw" | grep -qi "<html"; then
      echo "FAIL not shared / HTML response: $title ($id)" >&2
      rm -f "$raw"; failed=$((failed+1)); continue
    fi
  fi

  size="$(max_size_for "$dest")"
  ext="${out##*.}"
  case "$ext" in
    png)
      convert "$raw" -auto-orient -strip -resize "${size}x${size}>" "$out" ;;
    *)
      convert "$raw" -auto-orient -strip -resize "${size}x${size}>" \
        -sampling-factor 4:2:0 -quality 82 -interlace JPEG -colorspace sRGB "$out" ;;
  esac
  echo "ok  $dest  <-  $title"
  ok=$((ok+1))
done < "$MANIFEST"

echo
echo "converted: $ok   skipped (already present): $skipped   failed: $failed"
[[ "$failed" -eq 0 ]]
