#!/usr/bin/env bash
#
# Import photos from the shared "Devine Sportfishing / Images" Google Drive folder
# into public/images/, converting HEIC -> JPG and resizing for the web.
#
# Usage:
#   scripts/import-drive-images.sh            # download + convert anything missing
#   scripts/import-drive-images.sh --force    # re-download and re-convert everything
#
# Requirements: curl, python3 with `pip install pillow pillow-heif`
# (pillow-heif bundles the HEVC decoder that iPhone HEIC files need).
# Edit scripts/drive-images.manifest.tsv to change which photo goes where.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT/scripts/drive-images.manifest.tsv"
OUT_DIR="$ROOT/public/images"
CACHE_DIR="${DRIVE_CACHE_DIR:-$ROOT/.drive-cache}"
FORCE="${1:-}"

mkdir -p "$OUT_DIR" "$CACHE_DIR"

CONVERT="$ROOT/scripts/convert-image.py"
if ! python3 -c "import PIL, pillow_heif" 2>/dev/null; then
  echo "Missing Python deps. Run: pip install pillow pillow-heif" >&2; exit 1
fi

# Max long-edge size by destination. Large backgrounds get more pixels.
max_size_for() {
  case "$1" in
    hero/*|gallery/hero-bg.*|gallery/sunset-boat.*|gallery/boat-action.*) echo 2400 ;;
    logo*|press/*) echo 1600 ;;
    *) echo 1600 ;;
  esac
}

ok=0; skipped=0; failed=0
MAP_MD="$OUT_DIR/IMAGE-MAP.md"
{
  echo "# Image map"
  echo
  echo "Generated by \`scripts/import-drive-images.sh\` from \`scripts/drive-images.manifest.tsv\`."
  echo "Source: Google Drive > Devine Sportfishing > Images."
  echo
  echo "| Site path | Original Drive title | Drive link |"
  echo "|---|---|---|"
} > "$MAP_MD"

while IFS=$'\t' read -r id dest title; do
  [[ -z "${id:-}" || "$id" == \#* ]] && continue
  dest="${dest%$'\r'}"; title="${title%$'\r'}"
  out="$OUT_DIR/$dest"
  mkdir -p "$(dirname "$out")"
  echo "| \`/images/$dest\` | $title | https://drive.google.com/file/d/$id/view |" >> "$MAP_MD"

  if [[ -f "$out" && "$FORCE" != "--force" ]]; then
    skipped=$((skipped+1)); continue
  fi

  raw="$CACHE_DIR/$id"
  if [[ ! -s "$raw" || "$FORCE" == "--force" ]]; then
    # Files in the folder are shared "anyone with the link", so the public
    # download endpoint works without auth. -L follows the usercontent redirect.
    if ! curl -fsSL --retry 3 --retry-delay 2 \
        -o "$raw" "https://drive.google.com/uc?export=download&id=$id"; then
      echo "FAIL download: $title ($id)" >&2; failed=$((failed+1)); continue
    fi
    # Drive returns an HTML page instead of the file if sharing is off.
    if head -c 512 "$raw" | grep -qi "<html"; then
      echo "FAIL not shared / HTML response: $title ($id)" >&2
      rm -f "$raw"; failed=$((failed+1)); continue
    fi
  fi

  size="$(max_size_for "$dest")"
  if dims="$(python3 "$CONVERT" "$raw" "$out" "$size" 2>&1)"; then
    echo "ok  $dest ($dims)  <-  $title"
    ok=$((ok+1))
  else
    echo "FAIL convert: $title ($id): $dims" >&2; rm -f "$out"; failed=$((failed+1))
  fi
done < "$MANIFEST"

echo
echo "converted: $ok   skipped (already present): $skipped   failed: $failed"
[[ "$failed" -eq 0 ]]
